transport:
  mode: fs
  kafka:
    bootstrap_servers: "localhost:9092"

paths:
  data_root: "data"
  outputs: "data/outputs"
  topics_dir: "data/outputs/topics"
  models_dir: "data/outputs/models"

external_anomaly:
  min_support: 5
  ewma_alpha: 0.3
  threshold: 0.65
  recent_k: 200
  cooldown_minutes: 60

internal_anomaly:
  window: 28
  z_th: 2.0
  mad_th: 2.5
